### ISSUE TITLE
Mark as 1.20.5-1.20.6 compatible

### ISSUE THREAD

**Issue by nolight132** [Kira-NT/cubes-without-borders#11]
I saw this mod being included in a 1.20.6 modpack and wanted to try it out for myself. However, searching for the mod in Prism Launcher gave no results as it is not marked as 1.20.6-compatible. I just grabbed the latest version and it works perfectly fine.

I would make it a pull request but I am pretty sure one cannot interact with Modrinth/CurseForge versioning via a git repo.

**Comment by aoqia194** [comment]
I second this!

**Comment by Kira-NT** [comment]
Thanks a lot for the heads-up! I haven't been able to update all my mods to 1.20.5+ yet, so I didn't know that this one still works just fine :)

I've updated the list of supported versions on Modrinth and CF, so it should be fine now.

**Comment by aoqia194** [comment]
tsym!!!
