### ISSUE TITLE
Toggling F11 will not persist borderless state

### ISSUE THREAD

**Issue by Madis0** [Kira-NT/cubes-without-borders#2]
Using version 1.1.0+1.20 on Minecraft 1.20.4.
When the user toggles full screen with the keybind F11, the mod will toggle between normal fullscreen to normal windowed mode, borderless state is not remembered.

**Comment by Kira-NT** [comment]
Oh, right, I completely forgot that F11 is a thing :D Thank you for notifying me!

So, how the fullscreen toggle should work when there are 3 options available? What do you think will be the most convenient behavior for the end user?

**Comment by Madis0** [comment]
> So, how the fullscreen toggle should work when there are 3 options available? What do you think will be the most convenient behavior for the end user?

The most convenient would be to remember what the user chose last - ON or Borderless, default to ON.

1. So if I install the mod at first, F11 toggles between normal and disabled fullscreen mode. 
2. Once I manually set it to Borderless in video settings, it will toggle between borderless and disabled fullscreen mode. 
3. If I, at some point, change the toggle to ON again, it will toggle between normal and disabled full screen mode again.

**Comment by Kira-NT** [comment]
Okie, seems like a good design decision to me

**Comment by linux-universe** [comment]
> > So, how the fullscreen toggle should work when there are 3 options available? What do you think will be the most convenient behavior for the end user?
> 
> The most convenient would be to remember what the user chose last - ON or Borderless, default to ON.
> 
>     1. So if I install the mod at first, F11 toggles between normal and disabled fullscreen mode.
> 
>     2. Once I manually set it to Borderless in video settings, it will toggle between borderless and disabled fullscreen mode.
> 
>     3. If I, at some point, change the toggle to ON again, it will toggle between normal and disabled full screen mode again.

 I find this suggestion perfect

**Comment by Scubakay** [comment]
That's also how Borderless mining works. Looking for an alternative for it and this feature (plus actual development) would definitely make me switch!
