### ISSUE TITLE
Sometimes, minecraft is ALWAYS on top of other windows in windowed mode

### ISSUE THREAD

**Issue by slushieuwu** [Kira-NT/cubes-without-borders#21]
from here: https://github.com/Kir-Antipov/cubes-with-borders/issues/2

in this image, my browser is the focused application
![image](https://github.com/Kir-Antipov/cubes-without-borders/assets/86991346/a1e1987d-b209-4dc2-8997-c92a2f364deb)

**Comment by Kira-NT** [comment]
Thanks! Will look into it!

**Comment by Kira-NT** [comment]
So, I ended up rewriting the entire mod, and once I was done, I couldn't reproduce the problem, at least anymore. I guess I accidentally fixed it along the way :D
