### ISSUE TITLE
AMD dGPU on Windows causes the game to freeze

### ISSUE THREAD

**Issue by ibelieveinwhatileaveinthewaybehind** [Kira-NT/cubes-without-borders#22]
Hi!

I have been using this mod without an issue for several days now using my laptop's integrated GPU. I wanted to test out the performance difference between the iGPU and dGPU but can't get my game to work properly in borderless fullscreen when using the dGPU. Normal fullscreen and windowed mode work fine on the dGPU.

[Here is a video of the issue](https://github.com/Kir-Antipov/cubes-without-borders/assets/88601236/9990c7fc-3755-4d68-a935-591c2d787716).

As an aside, this is the weirdest bug I've come across, I think..

Thanks,
~Luke

**Comment by Kira-NT** [comment]
Oh. My. God. Windows is the gift that just keeps on giving, isn't it? Well, technically, there's some finicky stuff happening on the AMD drivers' side, but still, this isn't a problem on other platforms.

After quickly skimming through the internet, I found issues that AMD users had on Windows with some fullscreen apps, which sound similar to our case:

> AMD drivers were plagued with a bug throughout 2022 and much of 2023 which makes the screen freeze [...] when you make a game in the background fullscreen. [...] It was resolved months and many drivers later, but the 24.3.1 update brought it back and it's even worse now.

So, I guess, try downgrading or upgrading your drivers?

**Comment by Kira-NT** [comment]
I've reverted the default fullscreen mode used by CWB on Windows back to `windows:windowed`, which should help circumvent your issue.
