### ISSUE TITLE
Partial Regression : `v2.1.0` causes display resolution issues

### ISSUE THREAD

**Issue by Julienraptor02** [Kira-NT/cubes-without-borders#24]
Borderless Fullscreen still works as intended however Exclusive Fullscreen now has the #17 again
2.0.1 did correctly fix the bug for both Fullscreen modes

discovered due to a report on FO's discord and then tested by myself
\- @Julienraptor01 (alt)

**Comment by Julienraptor02** [comment]
Reverting 5c5f1f2f fixes it
[0001-Revert-Removed-the-fix-for-startup-resolution-issue.patch](https://github.com/user-attachments/files/16309282/0001-Revert-Removed-the-fix-for-startup-resolution-issue.patch)
[cubes-without-borders.build.libs.zip](https://github.com/user-attachments/files/16309265/cubes-without-borders.build.libs.zip)

**Comment by Kira-NT** [comment]
Thanks. I wanted to address other issues first, as this one is just a matter of reverting a reverted commit *(sigh)*, and it's not really relevant for borderless fullscreen mode, but I guess it is a big deal for modpacks, where not every user wants to use an alternative fullscreen mode. I'll push a quick fix in a minute then.
