### ISSUE TITLE
Color filters on Windows11 not working when Fullscreen

### ISSUE THREAD

**Issue by ghost** [Kira-NT/cubes-without-borders#28]
Multiple color filters (for example Grayscale, Grayscale inverted, tritanopia, protanopia, deuteranopia, and Inverted) do not work when in Fullscreen. This is affecting gameplay for me

Even when choosing Borderless as Fullscreen, it still has the same effects

I can't send demonstrative footage because Game Bar from Windows doesn't support it somehow

**Comment by Kira-NT** [comment]
I'm sorry to hear that! I hope that there's a mod somewhere in the wild that could substitute this feature for you in the meantime. Even I have one that plays around with colorblindness filters in my pile of unfinished projects. Surely somebody had to go all the way through with this idea.

Also, it's strange that Game Bar doesn't work for you, as I specifically checked it on my friend's machine, and it functioned just fine. However, my friend uses Win10, so this may be a Win11-specific issue. I guess I need to find someone unfortunate enough to daily drive Win11, so I can test things.

**Comment by Kira-NT** [comment]
I've reverted the default fullscreen mode used by CWB on Windows back to `windows:windowed`, and specifically tested that it doesn't interfere with color filtering - everything seems to work just fine now.
