### ISSUE TITLE
Not compatible with pip

### ISSUE THREAD

**Issue by 72888hshu** [Kira-NT/cubes-without-borders#29]
Minecraft version: 1.20.6
Mod Version: 2.1.0+1.20

What happen rn:
![image](https://github.com/user-attachments/assets/18f9a686-ee3c-4346-96c2-6afa2d4901c6)

What can happen if supporting pip:
![image](https://github.com/user-attachments/assets/9ef56cbd-ae68-4e21-ac18-bba391654890)
(This instance is using mod:Borderless Mining, which doesnt support 1.20.6 not 1.21)

**Comment by 72888hshu** [comment]
wait nevermind
![image](https://github.com/user-attachments/assets/a6561a12-4d2c-4bf8-9cc4-c35bf0705398)

**Comment by LittlePooh-Git** [comment]
Bro what are you watching ;-;
