### ISSUE TITLE
Game Menu opens when tabbing out

### ISSUE THREAD

**Issue by Exonerie** [Kira-NT/cubes-without-borders#35]
Is there any way of disabling the Main Menu Screen from popping up when you tab out of Minecraft?

**Comment by Kira-NT** [comment]
Huh? It's not supposed to do that! :D When did this start happening?

**Comment by Exonerie** [comment]
I've just recently started using this mod, so for me, it was since I started about 2 weeks ago.

When I press Alt + Tab, the game opens the “Game Menu”-screen after about a second.

Minecraft 1.21.1 (Using MC Version 1.21 also has the same effect.)
Fabric Loader 0.16.5
Cubes Without Borders 2.1.1+1.21

I'm playing with other mods, but using just this mod has the same behavior.

For Clarification: With “Game Menu”-screen I don't mean the title screen but the menu that opens when you hit ESC.

**Comment by Rasenm4her** [comment]
@Exonerie try hitting F3+P when in-Game, maybe you pressed that on accident, happend to me before. When it says "Pause on lost focus: disabled" if should work normally again (if that was the reason)

**Comment by Exonerie** [comment]
That fixed it, thank you!

**Comment by Kira-NT** [comment]
P.S. - I'm gonna expose this option via the upcoming configuration screen, allowing players to change this behavior more easily and intuitively :)

**Comment by Kira-NT** [comment]
Since `v3.0.0`, this option is now available through the mod's configuration screen.
