### ISSUE TITLE
Flash when switching windows

### ISSUE THREAD

**Issue by MrPerson8** [Kira-NT/cubes-without-borders#4]
There is a brief black flash when switching between MC Borderless and another monitor. Is this something that can be changed or is it just a part of the game?

**Comment by Kira-NT** [comment]
Yep, I know, and it annoys me as well. There's a GLFW[^1] bug[^2] with borderless fullscreen mode on Windows/X11 machines, which causes the screen to flicker whenever the app gains or loses focus.

It's been almost 10 years, and there are still no good solutions to it. The only "fix" that worked with Minecraft is not bringing its window into proper fullscreen mode, i.e., stretching it 1 pixel beyond the monitor's resolution. However, while this solution worked somewhat okay on my machine, my friend observed serious performance degradation on theirs. So, I removed this workaround from `v1.1.0` of this mod.

Though, you can try [`v1.0.0`](https://modrinth.com/mod/cubes-without-borders/versions), which still has it, and see if it works well for you. If it does, I may put it back in the mod hidden behind some toggle.

[^1]: [GLFW](https://en.wikipedia.org/wiki/GLFW), to put it simply, is a library that Minecraft uses to manage its window(s) and user input
[^2]: glfw/glfw#527

**Comment by CeIIHunter** [comment]
Please add this back into the mod. Your mod v1.0.0 is currently the only way I can play MC in fullscreen without it messing up my HDR settings.

**Comment by Kira-NT** [comment]
I checked again with my friend who initially reported the performance degradation, which led me to take the workaround down, and they don't seem to be able to reproduce it anymore. I guess they just got unlucky the first time, with Windows running something heavy in the background like updates or telemetry™.

Don't worry, you *currently* aren't missing out on any features or fixes. The only difference between v1.1.0 and v1.0.0 is that the workaround has been disabled, so in your case, it's literally the same mod, but worse :D I think I'm gonna take that version down.
