### ISSUE TITLE
Borderless always goes to the "Main" display

### ISSUE THREAD

**Issue by ModdingPink** [Kira-NT/cubes-without-borders#5]
Hey! 
Due to my setup I'm required to set my "Main" display to a different display than what my actual main display should be.
Could you implement support to change which display is used for borderless? 
Thanks!

**Comment by Kira-NT** [comment]
Hi! Yup, I can absolutely do that :) This needs a little bit more tinkering, as it is not as simple as with the "traditional" fullscreen, where you just tell your app to go to a specific monitor. Thus, I didn't implement this functionality for the first version of the mod. However, it absolutely is a valid use case, and I will support it.
